apiVersion: v1
kind: Namespace
metadata:
  name: tplus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tplus
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: $AWS_ECR_REPO/frontend:latest
        ports:
            - containerPort: 3000
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: tplus
  name: frontend-service
  labels:
    app: frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000