apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tplus
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backendn-container
        image: $AWS_ECR_REPO/backend:latest
        ports:
            - containerPort: 8081
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: tplus
  name: backend-service
  labels:
    app: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001