# mysql-statefulset.yaml to be reviewed

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: your_mysql_root_password # Replace 'your_mysql_root_password' with the desired root password
            - name: MYSQL_DATABASE
              value: your_database_name # Replace 'your_database_name' with your desired database name
            - name: MYSQL_USER
              value: your_mysql_user # Replace 'your_mysql_user' with your desired MySQL user
            - name: MYSQL_PASSWORD
              value: your_mysql_password # Replace 'your_mysql_password' with your desired MySQL user password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: your_storage_class_name # Replace 'your_storage_class_name' with the desired storage class name
        resources:
          requests:
            storage: 1Gi # Replace with the desired storage size


---
# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
