apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.backend.name }}-service"
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ template "helm-charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}