apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.db.name }}-service"
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.db.name }}
    chart: {{ template "helm-charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.db.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.db.name }}
    release: {{ .Release.Name }}