apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.db.name }}-pv-claim"
  namespace: {{ .Values.namespace.name }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{.Values.db.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

