name: Infrastructure Deployment


on:
  workflow_dispatch:
  push:
    branches:
     - master
     - main

permissions:
  id-token: write
  contents: read


jobs:

  #----------------------------------------------
  #-------Setup Infrastructure-------------------
  #----------------------------------------------

  provision-infrastructure-for-deployment:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      #----------------------------------------------
      # ----- Authenticate With AWS Credentials -----
      #----------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      #----------------------------------------------
      # --- Setup Terraform with specific version ---
      #----------------------------------------------
      - name: Setup Terraform
        run: |
          # change directory to /tmp to avoid conflicts with terraform folder containing the infrastruture code
          cd /tmp
          sudo apt install wget curl unzip
          TER_VER=`curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep tag_name | cut -d: -f2 | tr -d \"\,\v | awk '{$1=$1};1'`
          wget https://releases.hashicorp.com/terraform/${TER_VER}/terraform_${TER_VER}_linux_amd64.zip
          unzip terraform_${TER_VER}_linux_amd64.zip
          sudo mv -f terraform /bin/terraform
        # uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.3.7
        #   terraform_wrapper: false

      - name: Install Aws Cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: View versions of tools
        run: |
          echo "Terraform version: $(terraform version)"
          echo "Aws Cli Version: $(aws --version)"
    #----------------------------------------------
    #----  Setup Infrastructure   -----------------
    #----------------------------------------------

      - name: Terraform init
        run: |
          cd terraform
          terraform init -backend-config=backend.hcl
      - name: Terraform validate
        run: |
          cd terraform
          terraform validate
      - name: Terraform plan
        run: |
          cd terraform
          terraform plan
      - name: Terraform apply 
        run: |
          cd terraform
          terraform apply -target=module.vpc -target=module.dns -target=module.eks -auto-approve
          sleep 10
      - name: Terraform Apply -v2
        run: |
          cd terraform
          terraform apply -auto-approve
          mkdir -p ~/artifact
          echo $(terraform output --json ecr_repo_urls) > ~/artifact/ecr_repo_url.txt
          echo $(terraform output --raw kubectl_config) > ~/artifact/kubectl_config.txt
          # cat ~/artifact/ecr_repo_url.txt
          # cat ~/artifact/kubectl_config.txt 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: ~/artifact/*

    #----------------------------------------------
    #----  Build and Push to ECR   ---------------
    #----------------------------------------------

  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    needs: provision-infrastructure-for-deployment
    strategy:
      matrix:
        service:
          - frontend
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - loadgenerator
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          
   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

      #----------------------------------------------
      # ----- Authenticate With AWS Credentials -----
      #----------------------------------------------
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    #----------------------------------------------
    #      ----- Build, Tag & Push -----
    #----------------------------------------------

    - name: Download repo artifact
      uses: actions/download-artifact@v3
      with:
        name: repo-artifact
        path: downloaded-artifact

    - name: Display ecr_repo.txt
      run: |
        ls -R downloaded-artifact
        echo "The contents of the file are: $(cat downloaded-artifact/ecr_repo_url.txt)"

    # Read the output variable
    - name: Read output variable
      id: read-output-variable
      run: |
        value=$(cat downloaded-artifact/ecr_repo_url.txt)
        echo "The output value is $value"
    #----------------------------------------------
    #      ----- Ecr Login and Push -----
    #----------------------------------------------

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Pull, tag, and push Docker images
    - name: Pull, tag, and push frontend image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: frontend
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push adservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: adservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push cartservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: cartservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push checkoutservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: checkoutservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push currencyservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: currencyservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push emailservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: emailservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push loadgenerator image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: loadgenerator
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push paymentservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: paymentservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push productcatalogservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: productcatalogservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push recommendationservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: recommendationservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Pull, tag, and push shippingservice image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: talentplus
        IMAGE_TAG: shippingservice
        VERSION: v0.8.0
      run: |
        docker pull gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION
        docker tag gcr.io/google-samples/microservices-demo/$IMAGE_TAG:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    #----------------------------------------------
    #-------   Deployment to EKS -------------------
    #----------------------------------------------

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      #----------------------------------------------
      # ----- Authenticate With AWS Credentials -----
      #----------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      #----------------------------------------------
      # ----- Authenticate With EKS Cluster -----
      #----------------------------------------------
      - name: Download kubectl artifact
        uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: downloaded-artifact

      - name: Display kubectl_config
        run: |
          ls -R downloaded-artifact
          echo "The contents of the file are: $(cat downloaded-artifact/kubectl_config.txt)"
          cat downloaded-artifact/kubectl_config.txt > cluster.sh
          chmod +x cluster.sh
          ./cluster.sh
          cat ~/.kube/config | base64 -w0

      - name: Setup Kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin
          kubectl version -o yaml | grep gitVersion
          echo "All pods running in the cluster: $(kubectl get po -A)"

      - name: Setup Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          sudo ./get_helm.sh
          helm version

      - name: Install Aws Cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          
        #----------------------------------------------
        # ----- Deploy to EKS Cluster using Helm -----
        #----------------------------------------------

      - name: Deploy Applications
        run: |
          echo "Kubectl version: $(kubectl version --output=yaml)"
          kubectl get nodes
          echo "Deploying apps using helm charts && nothing to do next"
          helm upgrade --install talentplus-assessment helm-chart/
          sleep 60
          SERVICE_IP=$(kubectl get svc frontend-external -n talentplus -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "The Service External IP is: $SERVICE_IP"
          echo "SERVICE_IP=$SERVICE_IP" >> $GITHUB_ENV

      - name: Get Hosted Zone ID
        id: get-hosted-zone-id
        run: |
          HOSTED_ZONE_ID=$(aws route53 list-hosted-zones --query "HostedZones[?Name==\`eks.cgseerapps.com.\`].Id" --output text)
          echo "The Hosted Zone ID is: $HOSTED_ZONE_ID"
          HOSTED_ZON_ID=${HOSTED_ZONE_ID##*/}  # Remove '/hostedzone/' prefix
          echo "The Updated Hosted Zone ID is: $HOSTED_ZON_ID"
          echo "HOSTED_ZON_ID=$HOSTED_ZON_ID" >> $GITHUB_ENV

      # - name: Update Route 53 DNS
      #   run: |
      #     aws route53 change-resource-record-sets \
      #       --hosted-zone-id "$HOSTED_ZON_ID"  --change-batch "{
      #       \"Changes\": [
      #         {
      #           \"Action\": \"UPSERT\",
      #           \"ResourceRecordSet\": {
      #             \"Name\": \"eks.cgseerapps.com\",
      #             \"Type\": \"A\",
      #             \"AliasTarget\": {
      #               \"HostedZoneId\": \"$HOSTED_ZON_ID\",
      #               \"DNSName\": \"$SERVICE_IP\",
      #               \"EvaluateTargetHealth\": false
      #             }
      #           }
      #         }
      #       ]
      #     }"


